tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"

brew "autoconf"
brew "automake"
brew "coreutils"
brew "libtool"
brew "libyaml"
brew "openssl@1.1"
brew "readline"
brew "unixodbc"
brew "asdf"
brew "autojump"
brew "curl"
brew "ghostscript"
brew "git"
brew "gnupg"
brew "imagemagick"
brew "libxslt"
brew "macvim"
brew "mysql@5.7", restart_service: true
brew "postgresql"
brew "rbenv"
brew "redis", restart_service: true
brew "the_silver_searcher"
brew "unzip"
brew "wxmac"
brew "yarn"
brew "zplug"
brew "zsh"


cask "adobe-acrobat-reader"
cask "alfred"
cask "dash"
cask "docker"
cask "dropbox"
cask "firefox"
cask "flowdock"
cask "font-source-code-pro"
cask "google-cloud-sdk"
cask "iterm2"
cask "kobo"
cask "skype"
cask "slack"
cask "sourcetree"
cask "typora"
cask "zoom"
